<?php namespace Elihans\Http\Controllers;

/* Autogenerated Forum Controller */
/* Hook point of the Forum package inside your laravel application */
/* Feel free to override methods here to fit your requirements */

use Elihans\Http\Controllers\Auth\ForumAuth;

class ForumController extends \Riari\Forum\Controllers\BaseController
{

    use ForumAuth;
}
